In [1]:
from pipeline import Pipeline, Process, Postprocess, Preprocess
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import cv2
import os

In [2]:
class MyPreProcess(Preprocess):
    process_desc = "Exemple de pre-process -> ne fait rien"
    def run(self, images):
        pass


class MyProcess(Process):
    process_desc = "Exemple de process -> ne fait rien"
    def run(self, images):
        pass
    
    
class MyPostProcess(Postprocess):
    process_desc = "Exemple de post-process -> ne fait rien"
    def run(self, images):
        pass

In [3]:
pipeline = Pipeline()
process_array = np.array([MyPreProcess()
                          ,MyProcess()
                          ,MyPostProcess()
                          ,MyPreProcess(verbose=0)])
pipeline.add_processes(process_array)

Preprocess :  Exemple de pre-process -> ne fait rien
Process :  Exemple de process -> ne fait rien
Postprocess :  Exemple de post-process -> ne fait rien
Exemple de pre-process -> ne fait rien a été ajouté.
Exemple de process -> ne fait rien a été ajouté.
Exemple de post-process -> ne fait rien a été ajouté.
Exemple de pre-process -> ne fait rien a été ajouté.

In [4]:
pipeline.print_process()

Exemple de pre-process -> ne fait rien
Exemple de pre-process -> ne fait rien
Exemple de process -> ne fait rien
Exemple de post-process -> ne fait rien

In [3]:
data = pd.read_csv('/home/sid2018-6/Documents/proget_interpromo/Interpromo2020/Interpromo2020/All Data/SEATGURU_INFO_AIRCRAFT.csv',';')

In [4]:
data.head()

,Data_Source,Airline_name,Aircraft_Type,Category,Flight_Type,Count,Total_seat,Seat_Class,Seat_Type,Seat_Position,...,Width,Bedlength_maximum,Bedlength_minimum,Music,VideoType,Power_available,Power_kind,Usb_available,Usb_kind,Rating
0,SeatGuru,aegean-airlines,Airbus A319-100,ECONOMY,short haul,138,138,Economy,STANDARD,BULKHEAD,...,18.0,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,2
1,SeatGuru,aegean-airlines,Airbus A319-100,ECONOMY,short haul,138,138,Economy,STANDARD,NORMAL,...,18.0,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,2
2,SeatGuru,aegean-airlines,Airbus A319-100,ECONOMY,short haul,138,138,Economy,STANDARD,EXIT_ROW,...,18.0,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,5
3,SeatGuru,aegean-airlines,Airbus A319-100,ECONOMY,short haul,138,138,Economy,STANDARD,NORMAL,...,18.0,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,3
4,SeatGuru,aegean-airlines,Airbus A319-100,ECONOMY,short haul,138,138,Economy,STANDARD,NORMAL,...,18.0,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,1

In [5]:
print(data.columns)
print(data.shape)

Index(['Data_Source', 'Airline_name', 'Aircraft_Type', 'Category',
       'Flight_Type', 'Count', 'Total_seat', 'Seat_Class', 'Seat_Type',
       'Seat_Position', 'Recline', 'Premium', 'Pitch_minimum', 'Pitch_maximum',
       'Width', 'Bedlength_maximum', 'Bedlength_minimum', 'Music', 'VideoType',
       'Power_available', 'Power_kind', 'Usb_available', 'Usb_kind', 'Rating'],
      dtype='object')
(10330, 24)

In [6]:
dataetu = data[7070:8000]
dataetu

,Data_Source,Airline_name,Aircraft_Type,Category,Flight_Type,Count,Total_seat,Seat_Class,Seat_Type,Seat_Position,...,Width,Bedlength_maximum,Bedlength_minimum,Music,VideoType,Power_available,Power_kind,Usb_available,Usb_kind,Rating
7070,SeatGuru,peach,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,BULKHEAD,...,17,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,4
7071,SeatGuru,peach,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,NORMAL,...,17,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,3
7072,SeatGuru,peach,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,NORMAL,...,17,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,2
7073,SeatGuru,peach,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,EXIT_ROW,...,17,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,4
7074,SeatGuru,peach,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,EXIT_ROW,...,17,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,5
7075,SeatGuru,peach,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,NORMAL,...,17,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,1
7076,SeatGuru,pegasus-airlines,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,BULKHEAD,...,17,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,2
7077,SeatGuru,pegasus-airlines,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,NORMAL,...,17,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,3
7078,SeatGuru,pegasus-airlines,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,NORMAL,...,17,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,2
7079,SeatGuru,pegasus-airlines,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,EXIT_ROW,...,17,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,4
7080,SeatGuru,pegasus-airlines,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,EXIT_ROW,...,17,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,5
7081,SeatGuru,pegasus-airlines,Airbus A320-200,ECONOMY,short haul,180,180,Economy,STANDARD,NORMAL,...,17,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,1
7082,SeatGuru,pegasus-airlines,Airbus A320neo,ECONOMY,short haul,186,186,Economy,STANDARD,BULKHEAD,...,18,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,4
7083,SeatGuru,pegasus-airlines,Airbus A320neo,ECONOMY,short haul,186,186,Economy,STANDARD,NORMAL,...,18,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,3
7084,SeatGuru,pegasus-airlines,Airbus A320neo,ECONOMY,short haul,186,186,Economy,STANDARD,NORMAL,...,18,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,2
7085,SeatGuru,pegasus-airlines,Airbus A320neo,ECONOMY,short haul,186,186,Economy,STANDARD,EXIT_ROW,...,18,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,4
7086,SeatGuru,pegasus-airlines,Airbus A320neo,ECONOMY,short haul,186,186,Economy,STANDARD,EXIT_ROW,...,18,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,5
7087,SeatGuru,pegasus-airlines,Airbus A320neo,ECONOMY,short haul,186,186,Economy,STANDARD,NORMAL,...,18,NaN,NaN,NONE,NONE,NONE,NaN,NONE,NaN,1
7088,SeatGuru,pegasus-airlines,Boeing 737-800,ECONOMY,short haul,189,189,Economy,STANDARD,BULKHEAD,...,17.3,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,2
7089,SeatGuru,pegasus-airlines,Boeing 737-800,ECONOMY,short haul,189,189,Economy,STANDARD,NORMAL,...,17.3,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,3
7090,SeatGuru,pegasus-airlines,Boeing 737-800,ECONOMY,short haul,189,189,Economy,STANDARD,NORMAL,...,17.3,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,2
7091,SeatGuru,pegasus-airlines,Boeing 737-800,ECONOMY,short haul,189,189,Economy,STANDARD,EXIT_ROW,...,17.3,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,4
7092,SeatGuru,pegasus-airlines,Boeing 737-800,ECONOMY,short haul,189,189,Economy,STANDARD,EXIT_ROW,...,17.3,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,5
7093,SeatGuru,pegasus-airlines,Boeing 737-800,ECONOMY,short haul,189,189,Economy,STANDARD,BULKHEAD,...,17.3,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,4
7094,SeatGuru,pegasus-airlines,Boeing 737-800,ECONOMY,short haul,189,189,Economy,STANDARD,NORMAL,...,17.3,NaN,NaN,NONE,OVERHEAD,NONE,NaN,NONE,NaN,1
7095,SeatGuru,philippine-airlines,A350,BUSINESS,long haul,30,292,Business,FLAT_BED,NORMAL,...,21,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,ALL,PORT,2
7096,SeatGuru,philippine-airlines,A350,BUSINESS,long haul,30,292,Business,FLAT_BED,NORMAL,...,21,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,ALL,PORT,3
7097,SeatGuru,philippine-airlines,A350,PREMIUM,long haul,24,292,Premium Economy,STANDARD,BULKHEAD,...,19,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,ALL,PORT,2
7098,SeatGuru,philippine-airlines,A350,PREMIUM,long haul,24,292,Premium Economy,STANDARD,NORMAL,...,19,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,ALL,PORT,3
7099,SeatGuru,philippine-airlines,A350,ECONOMY,long haul,241,292,Economy,STANDARD,BULKHEAD,...,17,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,ALL,PORT,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7970,SeatGuru,saudia,Boeing 777-200,BUSINESS,long haul,38,232,Business,FLAT_BED,BULKHEAD,...,19.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7971,SeatGuru,saudia,Boeing 777-200,BUSINESS,long haul,38,232,Business,FLAT_BED,NORMAL,...,19.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7972,SeatGuru,saudia,Boeing 777-200,FIRST,long haul,24,232,First Class,FLAT_BED,NORMAL,...,21,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7973,SeatGuru,saudia,Boeing 777-200,ECONOMY,long haul,170,232,Guest,STANDARD,BULKHEAD,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,5
7974,SeatGuru,saudia,Boeing 777-200,ECONOMY,long haul,170,232,Guest,STANDARD,NORMAL,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,3
7975,SeatGuru,saudia,Boeing 777-200,ECONOMY,long haul,170,232,Guest,STANDARD,NORMAL,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,2
7976,SeatGuru,saudia,Boeing 777-200,ECONOMY,long haul,170,232,Guest,STANDARD,EXIT_ROW,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,4
7977,SeatGuru,saudia,Boeing 777-200,ECONOMY,long haul,170,232,Guest,STANDARD,BULKHEAD,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,4
7978,SeatGuru,saudia,Boeing 777-200,ECONOMY,long haul,170,232,Guest,STANDARD,NORMAL,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,1
7979,SeatGuru,saudia,Boeing 777-200 V2,BUSINESS,long haul,14,345,Business,FLAT_BED,BULKHEAD,...,19.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7980,SeatGuru,saudia,Boeing 777-200 V2,BUSINESS,long haul,14,345,Business,FLAT_BED,NORMAL,...,19.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7981,SeatGuru,saudia,Boeing 777-200 V2,ECONOMY,long haul,327,345,Guest,STANDARD,BULKHEAD,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,5
7982,SeatGuru,saudia,Boeing 777-200 V2,ECONOMY,long haul,327,345,Guest,STANDARD,NORMAL,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,3
7983,SeatGuru,saudia,Boeing 777-200 V2,ECONOMY,long haul,327,345,Guest,STANDARD,NORMAL,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,2
7984,SeatGuru,saudia,Boeing 777-200 V2,ECONOMY,long haul,327,345,Guest,STANDARD,BULKHEAD,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,4
7985,SeatGuru,saudia,Boeing 777-200 V2,ECONOMY,long haul,327,345,Guest,STANDARD,EXIT_ROW,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,4
7986,SeatGuru,saudia,Boeing 777-200 V2,ECONOMY,long haul,327,345,Guest,STANDARD,NORMAL,...,16.5-18,NaN,NaN,ON_DEMAND,ON_DEMAND,NONE,NaN,NONE,NaN,1
7987,SeatGuru,saudia,Boeing 777-300,FIRST,long haul,24,305,First Class,FLAT_BED,BULKHEAD,...,22.0,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7988,SeatGuru,saudia,Boeing 777-300,BUSINESS,long haul,36,305,Business,FLAT_BED,BULKHEAD,...,21.0,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7989,SeatGuru,saudia,Boeing 777-300,BUSINESS,long haul,36,305,Business,FLAT_BED,NORMAL,...,21.0,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7990,SeatGuru,saudia,Boeing 777-300,FIRST,long haul,24,305,First Class,FLAT_BED,NORMAL,...,22.0,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7991,SeatGuru,saudia,Boeing 777-300,ECONOMY,long haul,245,305,Economy,STANDARD,BULKHEAD,...,18.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,2
7992,SeatGuru,saudia,Boeing 777-300,ECONOMY,long haul,245,305,Economy,STANDARD,NORMAL,...,18.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7993,SeatGuru,saudia,Boeing 777-300,ECONOMY,long haul,245,305,Economy,STANDARD,EXIT_ROW,...,18.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,4
7994,SeatGuru,saudia,Boeing 777-300,ECONOMY,long haul,245,305,Economy,STANDARD,NORMAL,...,18.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,2
7995,SeatGuru,saudia,Boeing 777-300,ECONOMY,long haul,245,305,Economy,STANDARD,BULKHEAD,...,18.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,4
7996,SeatGuru,saudia,Boeing 777-300,ECONOMY,long haul,245,305,Economy,STANDARD,NORMAL,...,18.5,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,1
7997,SeatGuru,saudia,Boeing 777-300 V2,BUSINESS,long haul,30,413,Business,RECLINER,BULKHEAD,...,21.0,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7998,SeatGuru,saudia,Boeing 777-300 V2,BUSINESS,long haul,30,413,Business,RECLINER,NORMAL,...,21.0,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,3
7999,SeatGuru,saudia,Boeing 777-300 V2,ECONOMY,long haul,383,413,Guest,STANDARD,BULKHEAD,...,16.8,NaN,NaN,ON_DEMAND,ON_DEMAND,ALL,AC,NONE,NaN,4

In [7]:
list_type = dataetu['Aircraft_Type'].unique()
list_type

array(['Airbus A320-200', 'Airbus A320neo', 'Boeing 737-800', 'A350',
       'Airbus A320 B', 'Airbus A321', 'Airbus A330-300 V3',
       'Airbus A330 V3', 'Boeing 777-300ER', 'Q300', 'Q400',
       'A320-200 V1', 'Airlines Q400', 'Airways Airbus A330-200 B',
       'Airways Airbus A330-200 C', 'Airways Airbus A330-300',
       'Airways Airbus A380 B', 'Airways Boeing 717-200-125 new',
       'Airways Boeing 717-200 V3', 'Airways Boeing 737-800 V2',
       'Airways Boeing 747-400RR V2', 'Airways Boeing 747-400 4',
       'Airways Boeing 789', 'Airways Dash 8100', 'Airways Dash 8300',
       'Airways Q400', 'Airbus A319', 'Airbus A319 V2', 'Airbus A320 C',
       'Airbus A321 182pax', 'Airbus A321 196pax', 'Airbus A330-200 C',
       'Airbus A330-200 D', 'Airbus A330-200 F', 'Airbus A330-200 G',
       'Airbus A330-300', 'Airbus A330-300 B', 'Airbus A340-600',
       'Airbus A350', 'Airbus A350-900-Qsuites', 'Airbus A380',
       'Boeing 777-200LR', 'Boeing 777-200LR Qsuite',
       'Boeing 777-300ER Qsuite', 'Boeing 777-300ER V2',
       'Boeing 777-300ER V3', 'Boeing 787-8', 'QR Airbus A350-1000 V1',
       'SAAB 340B', '-800 D', 'A319-100 A', 'A319-100 B', 'A320-200 A',
       'A320-200 B', '737-800 A', '737-800 B', '737-800 C', '747-400 A',
       '747-400 B', '747-400 C', '777-300', '777-300ER', 'ATR 72-600',
       'Boeing 737-700', 'Boeing 767-300ER', 'Boeing 767-300ER Version 2',
       'Boeing 767-300ER Version 3', 'Embraer E-190', 'Airbus A320',
       'Airbus A320 V2', 'Airlines Boeing 787-8', 'Airbus A330',
       'Embraer 175', 'Embraer 195', 'A319 V2', 'A320', 'A321', '7-800',
       'Airlines Airbus A319', 'Airlines Airbus A320',
       'Airlines Airbus A320neo', 'Airlines Airbus A321',
       'Airlines Airbus A330 B', 'Airlines Airbus A340',
       'Airlines Boeing 737-600 B', 'Airlines Boeing 737-600 C',
       'Airlines Boeing 737-700', 'Airlines Boeing 737-700 B',
       'Airlines Boeing 737-800', 'Airlines Canadair CRJ900',
       'Airbus A330-300 V2', 'Boeing 747-400', 'Boeing 777-200',
       'Boeing 777-200 V2', 'Boeing 777-300', 'Boeing 777-300 V2'],
      dtype=object)

In [8]:
list_comp = dataetu['Airline_name'].unique()
list_comp

array(['peach', 'pegasus-airlines', 'philippine-airlines', 'porter',
       'qantas', 'qatar-airways', 'regional-express',
       'rossiya---russian-airlines', 'royal-air-maroc', 'royal-brunei',
       'royal-jordanian', 'ryanair', 's7-airlines', 'sas', 'saudia'],
      dtype=object)

In [9]:
data_plane = dataetu.groupby('Airline_name')['Aircraft_Type'].unique().apply(list).reset_index(name='Aircraft_Type_comp')
data_plane

,Airline_name,Aircraft_Type_comp
0,peach,[Airbus A320-200]
1,pegasus-airlines,"[Airbus A320-200, Airbus A320neo, Boeing 737-800]"
2,philippine-airlines,"[A350, Airbus A320 B, Airbus A321, Airbus A330..."
3,porter,[Airlines Q400]
4,qantas,"[Airways Airbus A330-200 B, Airways Airbus A33..."
5,qatar-airways,"[Airbus A319, Airbus A319 V2, Airbus A320 B, A..."
6,regional-express,[SAAB 340B]
7,rossiya---russian-airlines,"[-800 D, A319-100 A, A319-100 B, A320-200 A, A..."
8,royal-air-maroc,"[ATR 72-600, Boeing 737-700, Boeing 737-800, B..."
9,royal-brunei,"[Airbus A320, Airbus A320 V2, Airlines Boeing ..."
10,royal-jordanian,"[Airbus A319, Airbus A320, Airbus A321, Airbus..."
11,ryanair,[Boeing 737-800]
12,s7-airlines,"[A319 V2, A320, A321, 7-800]"
13,sas,"[Airlines Airbus A319, Airlines Airbus A320, A..."
14,saudia,"[Airbus A319, Airbus A320, Airbus A320 V2, Air..."

In [10]:
l = []
for i in range(len(data_plane)):
    l.append(len(data_plane['Aircraft_Type_comp'][i]))
data_plane['nb_aircraft_type'] = l
data_plane

,Airline_name,Aircraft_Type_comp,nb_aircraft_type
0,peach,[Airbus A320-200],1
1,pegasus-airlines,"[Airbus A320-200, Airbus A320neo, Boeing 737-800]",3
2,philippine-airlines,"[A350, Airbus A320 B, Airbus A321, Airbus A330...",9
3,porter,[Airlines Q400],1
4,qantas,"[Airways Airbus A330-200 B, Airways Airbus A33...",13
5,qatar-airways,"[Airbus A319, Airbus A319 V2, Airbus A320 B, A...",25
6,regional-express,[SAAB 340B],1
7,rossiya---russian-airlines,"[-800 D, A319-100 A, A319-100 B, A320-200 A, A...",13
8,royal-air-maroc,"[ATR 72-600, Boeing 737-700, Boeing 737-800, B...",8
9,royal-brunei,"[Airbus A320, Airbus A320 V2, Airlines Boeing ...",3
10,royal-jordanian,"[Airbus A319, Airbus A320, Airbus A321, Airbus...",7
11,ryanair,[Boeing 737-800],1
12,s7-airlines,"[A319 V2, A320, A321, 7-800]",4
13,sas,"[Airlines Airbus A319, Airlines Airbus A320, A...",12
14,saudia,"[Airbus A319, Airbus A320, Airbus A320 V2, Air...",11

In [11]:
sum(data_plane['nb_aircraft_type'])

112

In [12]:
list_img_SEATGURU = os.listdir('/home/sid2018-6/Documents/proget_interpromo/Interpromo2020/Interpromo2020/All Data/ANALYSE IMAGE/LAYOUT SEATGURU')
len(list_img_SEATGURU)

1195

In [14]:
# Test template matching

#img_rgb = cv2.imread('/home/sid2018-6/Documents/proget_interpromo/Interpromo2020/Interpromo2020/All Data/ANALYSE IMAGE/LAYOUT SEATGURU/Aegean_Airlines_Airbus_A320-200_plane2.svg.png')
#img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)
#template = cv2.imread('/home/sid2018-6/Documents/proget_interpromo/Interpromo2020/Interpromo2020/All Data/ANALYSE IMAGE/images.png',0)
#w, h = template.shape[::-1]

#res = cv2.matchTemplate(img_gray,template,cv2.TM_CCOEFF_NORMED)
#threshold = 0.8
#loc = np.where( res >= threshold)
#for pt in zip(*loc[::-1]):
#    cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (0,0,255), 2)

#cv2.imwrite('res.png',img_rgb)

# Normé images: